DnAStore/DnAStore/Models/User.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DnAStore.Models
{
    public class User : IdentityUser
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool SpaceTravelCertified { get; set; }
    }
}

DnAStore/DnAStore/Pages/User/Profile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DnAStore.Models;
using DnAStore.Models.Interfaces;

namespace DnAStore.Pages.User
{
	[Authorize(Roles = "Member")]
	public class ProfileModel : PageModel
    {

		private UserManager<Models.User> _userManager;

        private IOrderManager _orderManager;

		public bool OnPasswordFailure = false;

		[BindProperty]
		public Models.User AppUser { get; set; }

		[BindProperty]
		public string OldPass { get; set; }

		[BindProperty]
		public string NewPass { get; set; }

		[BindProperty]
		public string ConfirmPass { get; set; }

        public List<Order> Orders { get; set; }

		// Constructor
		public ProfileModel(UserManager<Models.User> userManager, IOrderManager orderManager)
		{
			_userManager = userManager;
            _orderManager = orderManager;
		}

        public async Task OnGet()
        {
			string nameOfCurrentUser = User.Identity.Name;
			AppUser = await _userManager.FindByNameAsync(nameOfCurrentUser);
            Orders = await _orderManager.GetUserLastFiveEager(nameOfCurrentUser);
		}

		public async Task<IActionResult> OnPostAsync()
		{
			if (!ModelState.IsValid)
			{
				return Page();
			}

			string nameOfCurrentUser = User.Identity.Name;
			var user = await _userManager.FindByNameAsync(nameOfCurrentUser);

			user.FirstName = AppUser.FirstName;
			user.LastName = AppUser.LastName;

			await _userManager.UpdateAsync(user);

			return RedirectToPage();
		}

		public async Task<IActionResult> OnPostChangePassword()
		{
			string nameOfCurrentUser = User.Identity.Name;
			AppUser = await _userManager.FindByNameAsync(nameOfCurrentUser);

			if (NewPass.Equals(ConfirmPass))
			{
				await _userManager.ChangePasswordAsync(AppUser, OldPass, NewPass);
				return RedirectToPage();
			}
			else
			{
				OnPasswordFailure = true;
			}

			await OnGet();
			return Page();
		}
	}
}

DnAStore/DnAStore/Pages/User/Profile.cshtml
@page
@model DnAStore.Pages.User.ProfileModel

@using DnAStore.Models
@using Microsoft.AspNetCore.Identity;
@inject UserManager<User> UserMgr

@{
    ViewData["Title"] = "Account";
    Layout = "_Layout";

    string nameOfCurrentUser = User.Identity.Name;
    var user = await UserMgr.FindByNameAsync(nameOfCurrentUser);
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Account</title>
</head>
<body>

    <h2>Welcome, @user.FirstName!</h2>
    <br />

    <h4>Account Details</h4>
    <hr />

    <div class="row">
        <div class="col-md-4">
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="AppUser.Id" />
                <div class="form-group">
                    <label asp-for="AppUser.FirstName" class="control-label">First Name</label>
                    <input asp-for="AppUser.FirstName" class="form-control" />
                    <span asp-validation-for="AppUser.FirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AppUser.LastName" class="control-label">Last Name</label>
                    <input asp-for="AppUser.LastName" class="form-control" />
                    <span asp-validation-for="AppUser.LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AppUser.Email" class="control-label">Email Address</label>
                    <input asp-for="AppUser.Email" class="form-control" readonly />
                    <span asp-validation-for="AppUser.Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    @if (Model.OnPasswordFailure)
    {
        <p>Something went wrong. New and confirmed password must match.</p>
    }

    <div class="row">
        <div class="col-md-4">
            <form asp-page-handler="ChangePassword" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="AppUser.Id" />
                <div class="form-group">
                    <label asp-for="OldPass" class="control-label">Current Password</label>
                    <input asp-for="OldPass" class="form-control" type="password" />
                    <span asp-validation-for="OldPass" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="NewPass" class="control-label">New Password</label>
                    <input asp-for="NewPass" class="form-control" type="password" />
                    <span asp-validation-for="NewPass" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ConfirmPass" class="control-label">Confirm Password</label>
                    <input asp-for="ConfirmPass" class="form-control" type="password" />
                    <span asp-validation-for="ConfirmPass" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <h4>Your Recent Orders</h4>
    <hr />
    @if (Model.Orders.Count > 1)
    {
        @foreach (var order in Model.Orders)
        {
            <p><strong>@order.OrderDateTime</strong></p>
            <table>
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Item Price</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var oi in order.OrderItems)
                    {
                        <tr>
                            <td>@oi.Product.Name</td>
                            <td>@oi.Quantity</td>
                            <td>$@oi.Product.Price</td>
                        </tr>
                    }
                </tbody>
            </table>
            <p><strong>Order total: $@order.FinalTotal</strong></p>
            <hr />
        }
    }
    else
    {
        <p>You haven't placed any orders yet!</p>
        <a href="/Shop/Shop" class="btn">Shop</a>
    }
</body>
</html>