DnAStore/DnAStore/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DnAStore.Models;
using DnAStore.Models.Interfaces;
using DnAStore.Models.ViewModels;
using Microsoft.AspNetCore.Identity;

namespace DnAStore.Controllers
{
	public class BasketController : Controller
	{
		private readonly IBasketManager _basketManager;
		private readonly IBasketItemManager _basketItemManager;
		private SignInManager<User> _signInManager;

		// Constructor
		public BasketController(IBasketManager basketManager, IBasketItemManager basketItemManager, SignInManager<User> signInManager)
		{
			_basketManager = basketManager;
			_basketItemManager = basketItemManager;
			_signInManager = signInManager;
		}

		[HttpPost]
		public async Task<IActionResult> AddToBasket(int productId, string username)
		{
			if (!_signInManager.IsSignedIn(User))
			{
				return RedirectToAction("Login", "Account");
			}

			//Get user's basket by username
			Basket basket = await _basketManager.FindBasketByUserLazy(username);

			// If basket for user doesn't exist yet, create one
			if (basket == null)
			{
				basket = new Basket()
				{
					ID = 0,
					UserName = username,
					Subtotal = 0,
					BasketItems = new List<BasketItem>()
				};

				await _basketManager.CreateBasket(basket);

				// Gets the new basket with assigned ID from DB
				basket = await _basketManager.FindBasketByUserLazy(username);
			}

			// Check basketitems basket ID and product ID
			BasketItem basketItem = await _basketItemManager.FindBasketItem(basket.ID, productId);

			// If item doesn't already exist, create it; otherwise update it
			if (basketItem == null)
			{
				basketItem = new BasketItem()
				{
					ID = 0,
					BasketID = basket.ID,
					ProductID = productId,
					Quantity = 1
				};

				await _basketItemManager.CreateBasketItem(basketItem);
			}
			else
			{
				basketItem.Quantity++;
				await _basketItemManager.UpdateBasketItem(basketItem);
			}
			// Redirect to Shop action on Shop page
			return RedirectToAction("Shop", "Shop");
		}

		[HttpGet]
		public async Task<IActionResult> ViewBasket()
		{
			string username = HttpContext.User.Identity.Name;
			
			//Get user's basket by username
			Basket basket = await _basketManager.FindBasketByUserEager(username);

			// If basket for user doesn't exist yet, create empty one, but don't add it to DB
			if (basket == null)
			{
				basket = new Basket()
				{
					ID = 0,
					UserName = username,
					Subtotal = 0,
					BasketItems = new List<BasketItem>()
				};
			}
            else
            {
                basket.CalcSubtotal();
                await _basketManager.UpdateBasket(basket);
            }
			return View(basket);
		}

		[HttpPost]
		public async Task<IActionResult> EditBasketItemQuantity(int basketItemId, int qty)
		{
			if (qty < 1)
			{
				return RemoveBasketItem(basketItemId);
			}

			var basketItem = await _basketItemManager.FindBasketItem(basketItemId);

			if (basketItem == null)
			{
				return NotFound();
			}

			// Update quantity property of basket item with new qty
			basketItem.Quantity = qty;

			await _basketItemManager.UpdateBasketItem(basketItem);

			return RedirectToAction(nameof(ViewBasket));
		}

		[HttpPost]
		public IActionResult RemoveBasketItem(int basketItemId)
		{
			_basketItemManager.DeleteBasketItem(basketItemId);

			return RedirectToAction(nameof(ViewBasket));
		}
	}
}

DnAStore/DnAStore/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DnAStore.Models;
using DnAStore.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace DnAStore.Controllers
{
    public class ShopController : Controller
    {

		private readonly IProductManager _inventory;

		public ShopController(IProductManager inventory)
		{
			_inventory = inventory;
		}

		/// <summary>
		/// Route to Shop view
		/// </summary>
		/// <returns>Shop view</returns>
        public async Task<IActionResult> Shop()
        {
			List<Product> products = await _inventory.GetAllProducts();
			return View(products);
        }

		/// <summary>
		/// Route to product's Details view
		/// </summary>
		/// <param name="id">product ID</param>
		/// <returns>asynchronous task</returns>
		public async Task<IActionResult> Details(int id)
		{
			if (id < 1)
			{
				return NotFound();
			}

			var product = await _inventory.GetProductByID(id);

			if (product == null)
			{
				return NotFound();
			}

			return View(product);
		}
	}
}

DnAStore/DnAStore/Views/Shop/Details.cshtml
@model DnAStore.Models.Product
@{
    ViewData["Title"] = "Product Details";
    Layout = "_Layout";
}

<h2>Product Details</h2>
<br />

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(p => p.Name)
            </th>
            <th>
                @Html.DisplayNameFor(p => p.Price)
            </th>
            <th>
                @Html.DisplayNameFor(p => p.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(p => p.Name)
            </td>
            <td>
                $@Html.DisplayFor(p => p.Price)
            </td>
            <td>
                @Html.DisplayFor(p => p.Description)
            </td>
            <td>
                <form method="post" asp-controller="Basket" asp-action="AddToBasket">
                    <input type="hidden" name="username" value="@User.Identity.Name" readonly />
                    <input type="hidden" name="productId" value="@Model.ID" readonly />
                    <button type="submit" value="AddToBasket" class="btn">Add to Basket</button>
                    <a href="/Shop/Shop" class="btn">Back to Shop</a>
                </form>
            </td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td>
                <img src="@Html.DisplayFor(p => p.Image)" title="@Html.DisplayFor(p => p.Name)" width="400" class="ctr-img" />
            </td>
            <td></td>
        </tr>
    </tbody>
</table>

DnAStore/DnAStore/Views/Shop/Shop.cshtml
@model IEnumerable<DnAStore.Models.Product>

@{
    ViewData["Title"] = "Shop";
    Layout = "_Layout";
}

<h2>Shop</h2>
<br />

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(product => product.Name)
            </th>
            <th>
                @Html.DisplayNameFor(product => product.Price)
            </th>
            <th>
                @Html.DisplayNameFor(product => product.Description)
            </th>
            <th>
                @Html.DisplayNameFor(product => product.Image)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    $@Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @item.Description.Substring(0, 500)...
                </td>
                <td>
                    <img src="@Html.DisplayFor(modelItem => item.Image)" title="@Html.DisplayFor(modelItem => item.Name)" width="200" />
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.ID" class="btn">View Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

DnAStore/DnAStore/Views/Shop/ViewBasket.cshtml
@model DnAStore.Models.Basket
@{
    ViewData["Title"] = "View Basket";
    Layout = "_Layout";
}

<hr />
<p>
    <a href="/Shop/Shop">Back to Shop</a>
</p>
@if (Model.BasketItems.Count == 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.BasketItems[0].Product.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BasketItems[0].Product.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BasketItems[0].Quantity)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.BasketItems)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Product.Name)
                    </td>
                    <td>
                        $@Html.DisplayFor(modelItem => item.Product.Price)
                    </td>
                    <td>
                        <input type="number" name="UpdatedQty" value="@item.Quantity" />
                    </td>
                    <td>
                        @*<a asp-action="Edit" asp-route-id="@item.ID">Change Quantity</a> |*@
                        <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.ID">Delete Item</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <span>Your basket is currently empty</span>
}